// D11-C3 — Roster Management Server Boundary: registerRosterEntries()
// D11-C6 §4/§5: rewritten after removing the unsafe "multi-row INSERT ...
// RETURNING preserves input order" assumption. studentId/enrollmentId are
// now generated by the application (crypto.randomUUID()) before either
// insert happens, so correctness no longer depends on what shape a fake
// client's insert() response takes — these tests assert against the actual
// insert *payloads* captured by the fake client instead of against
// hand-picked "returned row" fixtures.
//
// registerRosterEntries()는 SupabaseClient를 직접 받는 순수 오케스트레이션
// 함수다(teacher-class-creation.ts와 동일한 스타일). ad-hoc fake
// SupabaseClient로 student/enrollment 두 테이블의 insert/select/delete
// 체인을 구성한다(ai-learning-analysis.test.ts/teacher-class-creation.test.ts와
// 동일한 스타일 — 새 mock 아키텍처를 도입하지 않는다).
import { describe, test, expect, vi } from 'vitest';
import type { SupabaseClient } from '@supabase/supabase-js';
import { registerRosterEntries, type RegisterRosterEntry } from '../../src/server/teacher-roster-creation';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

type WriteOutcome = { kind: 'ok' } | { kind: 'error'; error: unknown };
type EnrollmentWriteOutcome = { kind: 'ok' } | { kind: 'collision' } | { kind: 'error'; error: unknown };

function makeFakeClient(config: {
  existingStudentNos?: string[];
  studentInsertOutcome?: WriteOutcome;
  enrollmentInsertOutcome?: EnrollmentWriteOutcome;
  deleteOutcome?: WriteOutcome;
}) {
  const calls = {
    precheck: [] as { classId: string; studentNos: string[] }[],
    studentInsert: [] as { student_id: string; name: string }[][],
    enrollmentInsert: [] as { enrollment_id: string; student_id: string; class_id: string; student_no: string }[][],
    studentDelete: [] as string[][],
  };

  const client = {
    from(table: string) {
      if (table === 'enrollment') {
        return {
          select() {
            return {
              eq(_col: string, classId: string) {
                return {
                  async in(_col2: string, studentNos: string[]) {
                    calls.precheck.push({ classId, studentNos });
                    const existing = config.existingStudentNos ?? [];
                    return { data: existing.filter((n) => studentNos.includes(n)).map((n) => ({ student_no: n })), error: null };
                  },
                };
              },
            };
          },
          insert(rows: { enrollment_id: string; student_id: string; class_id: string; student_no: string }[]) {
            calls.enrollmentInsert.push(rows);
            const outcome = config.enrollmentInsertOutcome ?? { kind: 'ok' as const };
            if (outcome.kind === 'ok') return Promise.resolve({ data: null, error: null });
            if (outcome.kind === 'collision') {
              return Promise.resolve({
                data: null,
                error: { code: '23505', message: 'duplicate key value violates unique constraint "enrollment_class_id_student_no_key"' },
              });
            }
            return Promise.resolve({ data: null, error: outcome.error });
          },
        };
      }
      if (table === 'student') {
        return {
          insert(rows: { student_id: string; name: string }[]) {
            calls.studentInsert.push(rows);
            const outcome = config.studentInsertOutcome ?? { kind: 'ok' as const };
            if (outcome.kind === 'ok') return Promise.resolve({ data: null, error: null });
            return Promise.resolve({ data: null, error: outcome.error });
          },
          delete() {
            return {
              async in(_col: string, studentIds: string[]) {
                calls.studentDelete.push(studentIds);
                const outcome = config.deleteOutcome ?? { kind: 'ok' as const };
                if (outcome.kind === 'ok') return { error: null };
                return { error: outcome.error };
              },
            };
          },
        };
      }
      throw new Error(`unexpected table in fake client: ${table}`);
    },
  } as unknown as SupabaseClient;

  return { client, calls };
}

const CLASS_ID = 'class-1';

describe('registerRosterEntries — Case A/B (successful registration)', () => {
  test('A: single valid entry -> student + enrollment created, identity is application-generated and consistent across both inserts', async () => {
    const { client, calls } = makeFakeClient({});

    const result = await registerRosterEntries(client, CLASS_ID, [{ studentNo: '1', name: '김민준' }]);

    expect(result.status).toBe('ok');
    if (result.status !== 'ok') throw new Error('unreachable');
    expect(result.entries).toEqual([{ studentId: expect.stringMatching(UUID_RE), enrollmentId: expect.stringMatching(UUID_RE), studentNo: '1', name: '김민준' }]);

    // 응답이 실제로 두 insert에 보낸 값과 동일한지(상관관계가 애플리케이션이
    // 만든 값 자체이지, DB 응답 순서에서 추론된 값이 아님을 직접 확인한다).
    const created = result.entries[0];
    expect(calls.studentInsert[0]).toEqual([{ student_id: created.studentId, name: '김민준' }]);
    expect(calls.enrollmentInsert[0]).toEqual([{ enrollment_id: created.enrollmentId, student_id: created.studentId, class_id: CLASS_ID, student_no: '1' }]);
  });

  test('B: bulk valid entries -> all created in one batch each, response order matches input order, no two entries share an id', async () => {
    const { client, calls } = makeFakeClient({});
    const entries: RegisterRosterEntry[] = [
      { studentNo: '1', name: '김민준' },
      { studentNo: '2', name: '이서연' },
      { studentNo: '3', name: '박지호' },
    ];

    const result = await registerRosterEntries(client, CLASS_ID, entries);

    expect(result.status).toBe('ok');
    if (result.status !== 'ok') throw new Error('unreachable');
    expect(result.entries).toHaveLength(3);
    // D11-C6 회귀 방지: 응답 순서가 입력 순서와 정확히 대응해야 한다(어떤
    // DB RETURNING 순서에도 의존하지 않고, prepared 배열 자체가 순서를
    // 보존하기 때문에 항상 성립해야 하는 불변조건).
    expect(result.entries.map((e) => e.studentNo)).toEqual(['1', '2', '3']);
    expect(result.entries.map((e) => e.name)).toEqual(['김민준', '이서연', '박지호']);

    const studentIds = result.entries.map((e) => e.studentId);
    const enrollmentIds = result.entries.map((e) => e.enrollmentId);
    expect(new Set(studentIds).size).toBe(3); // 서로 다른 studentId
    expect(new Set(enrollmentIds).size).toBe(3);

    expect(calls.studentInsert[0]).toHaveLength(3); // 하나의 multi-row insert
    expect(calls.enrollmentInsert[0]).toHaveLength(3);
    // enrollment insert 페이로드의 student_id가 정확히 그 studentNo에 대응하는
    // studentId와 일치하는지 — 이게 바로 D11-C3가 index 상관관계로만
    // (암묵적으로) 보장하려던 것을, 이제 값 자체로 명시적으로 보장한다.
    for (let i = 0; i < 3; i++) {
      expect(calls.enrollmentInsert[0][i]).toEqual({
        enrollment_id: enrollmentIds[i],
        student_id: studentIds[i],
        class_id: CLASS_ID,
        student_no: entries[i].studentNo,
      });
    }
  });
});

describe('registerRosterEntries — Case C/D/E (all-or-nothing validation)', () => {
  test('C: one entry missing name -> validation-failed, zero DB writes', async () => {
    const { client, calls } = makeFakeClient({});
    const entries: RegisterRosterEntry[] = [
      { studentNo: '1', name: '김민준' },
      { studentNo: '2', name: '' },
    ];

    const result = await registerRosterEntries(client, CLASS_ID, entries);

    expect(result.status).toBe('validation-failed');
    if (result.status === 'validation-failed') {
      expect(result.errors).toEqual([{ index: 1, studentNo: '2', reason: 'missing-name' }]);
    }
    expect(calls.studentInsert).toHaveLength(0);
    expect(calls.enrollmentInsert).toHaveLength(0);
  });

  test('D: duplicate studentNo within the same batch -> validation-failed on the second occurrence, zero DB writes', async () => {
    const { client, calls } = makeFakeClient({});
    const entries: RegisterRosterEntry[] = [
      { studentNo: '5', name: '김민준' },
      { studentNo: '5', name: '이서연' },
    ];

    const result = await registerRosterEntries(client, CLASS_ID, entries);

    expect(result.status).toBe('validation-failed');
    if (result.status === 'validation-failed') {
      expect(result.errors).toEqual([{ index: 1, studentNo: '5', reason: 'duplicate-student-no' }]);
    }
    expect(calls.studentInsert).toHaveLength(0);
  });

  test('E: studentNo already registered in this class (DB pre-check) -> validation-failed, zero DB writes', async () => {
    const { client, calls } = makeFakeClient({ existingStudentNos: ['7'] });

    const result = await registerRosterEntries(client, CLASS_ID, [{ studentNo: '7', name: '최유진' }]);

    expect(result.status).toBe('validation-failed');
    if (result.status === 'validation-failed') {
      expect(result.errors).toEqual([{ index: 0, studentNo: '7', reason: 'duplicate-student-no' }]);
    }
    expect(calls.studentInsert).toHaveLength(0);
  });

  test('empty entries array -> empty-entries, zero DB calls attempted (no precheck either)', async () => {
    const { client, calls } = makeFakeClient({});

    const result = await registerRosterEntries(client, CLASS_ID, []);

    expect(result).toEqual({ status: 'empty-entries' });
    expect(calls.precheck).toHaveLength(0);
    expect(calls.studentInsert).toHaveLength(0);
  });
});

describe('registerRosterEntries — Case F/G (scoping and allowed duplicates)', () => {
  test('F: pre-check is scoped to the given classId (other classes\' studentNo usage is irrelevant)', async () => {
    // existingStudentNos는 findExistingStudentNos()가 실제로는
    // .eq('class_id', classId)로 스코프된 쿼리 결과라는 계약을 나타낸다 —
    // 여기서는 "이 classId에서는 비어있음"을 표현해 성공해야 함을 보인다.
    const { client, calls } = makeFakeClient({ existingStudentNos: [] });

    const result = await registerRosterEntries(client, CLASS_ID, [{ studentNo: '1', name: '김민준' }]);

    expect(result.status).toBe('ok');
    expect(calls.precheck[0].classId).toBe(CLASS_ID);
  });

  test('G: identical name across two entries is not an error (동명이인 허용) and each still gets a distinct studentId', async () => {
    const { client } = makeFakeClient({});

    const result = await registerRosterEntries(client, CLASS_ID, [
      { studentNo: '1', name: '김민준' },
      { studentNo: '2', name: '김민준' },
    ]);

    expect(result.status).toBe('ok');
    if (result.status !== 'ok') throw new Error('unreachable');
    expect(result.entries[0].studentId).not.toBe(result.entries[1].studentId);
    expect(result.entries.map((e) => e.name)).toEqual(['김민준', '김민준']);
    expect(result.entries.map((e) => e.studentNo)).toEqual(['1', '2']);
  });
});

describe('registerRosterEntries — Case K/L/M/N (insert failure and compensation)', () => {
  test('K: student insert fails -> insert-failed, enrollment insert never attempted', async () => {
    const { client, calls } = makeFakeClient({
      studentInsertOutcome: { kind: 'error', error: { message: 'connection reset' } },
    });

    const result = await registerRosterEntries(client, CLASS_ID, [{ studentNo: '1', name: '김민준' }]);

    expect(result).toEqual({ status: 'insert-failed' });
    expect(calls.enrollmentInsert).toHaveLength(0);
  });

  test('L: enrollment insert fails (non-collision) -> enrollment-failed, exactly the studentIds this request created are compensated', async () => {
    const { client, calls } = makeFakeClient({
      enrollmentInsertOutcome: { kind: 'error', error: { code: '42501', message: 'permission denied' } },
    });

    const result = await registerRosterEntries(client, CLASS_ID, [{ studentNo: '1', name: '김민준' }]);

    expect(result).toEqual({ status: 'enrollment-failed' });
    expect(calls.studentDelete).toHaveLength(1);
    // 삭제 대상은 이번 요청이 만든 student_id와 정확히 같아야 한다(다른
    // 요청/기존 row를 건드릴 방법이 구조적으로 없음을 확인).
    expect(calls.studentDelete[0]).toEqual(calls.studentInsert[0].map((r) => r.student_id));
  });

  test('M: enrollment UNIQUE race (23505 after passing pre-check) -> duplicate-conflict, created students compensated', async () => {
    const { client, calls } = makeFakeClient({
      enrollmentInsertOutcome: { kind: 'collision' },
    });

    const result = await registerRosterEntries(client, CLASS_ID, [{ studentNo: '1', name: '김민준' }]);

    expect(result).toEqual({ status: 'duplicate-conflict' });
    expect(calls.studentDelete[0]).toEqual(calls.studentInsert[0].map((r) => r.student_id));
  });

  test('N: compensating delete also fails -> still a controlled result (no DB detail leaked), failure is logged with exactly this request\'s studentIds', async () => {
    const logSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    try {
      const { client, calls } = makeFakeClient({
        enrollmentInsertOutcome: { kind: 'error', error: { message: 'insert failed' } },
        deleteOutcome: { kind: 'error', error: { message: 'delete failed too' } },
      });

      const result = await registerRosterEntries(client, CLASS_ID, [{ studentNo: '1', name: '김민준' }]);

      expect(result).toEqual({ status: 'enrollment-failed' });
      expect(logSpy).toHaveBeenCalledTimes(1);
      const [tag, context] = logSpy.mock.calls[0];
      expect(tag).toContain('[teacher-roster-creation]');
      expect(context).toEqual({ studentIds: calls.studentInsert[0].map((r) => r.student_id) });
    } finally {
      logSpy.mockRestore();
    }
  });
});
